### ISSUE TITLE
Missing tool: gmx check

### ISSUE THREAD

**Issue by Agnes-Petit** [galaxycomputationalchemistry/galaxy-tools-compchem#151]
Hello,
In my job, I need the gmx check tool from GROMACS on Galaxy. I saw that it is currently not available.
Have you started or plan to adapt it to Galaxy? If the answer is no, I would like to adapt it.

**Comment by simonbray** [comment]
Hi @Agnes-Petit, it is not an entire protein. but a five-residue peptide, in order to save space and compute resources. The peptide structure is in `str_ions.gro`. If it helps you can also use `gmx editconf -f test-data/npt.tpr -o peptide.pdb` to generate a PDB file.

**Comment by Agnes-Petit** [comment]
Hi, the gmx check script is ready however after discussion with my team, it appears that we want to include the team name in the owner of the .shed.yml. So we decided to publish the tool in the IUC directory. However if you have another solution to make the name of my team in the owner, we remain open to any suggestion.

**Comment by simonbray** [comment]
Hi @Agnes-Petit, the only reason for the 'owner' attribute in the .shed.yml file is to specify the user on the toolshed (app store for Galaxy tools). All the tools on this repo are uploaded by 'chemteam' as part of continuous integration when the PR is merged, which is the recommended way to create Galaxy tools. You can see also that on IUC all the .shed.yml files specify `owner: iuc`.

We don't want to claim ownership of any tool, we want to create a community that anyone can contribute to. :)

You can add yourself and team members to the maintainers section here if that helps? https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/blob/master/tools/gromacs/.shed.yml#L18

**Comment by Agnes-Petit** [comment]
Hi @simonbray, this solution suits us. I make the pull request.

**Comment by simonbray** [comment]
Added in #157
