### ISSUE TITLE
[WIP] Usability of all tools

### ISSUE THREAD

**Issue by chrisbarnettster** [galaxycomputationalchemistry/galaxy-tools-compchem#31]
Cross-validation of all tools. 
test tools you didn't create and give feedback. Bugs, typos, issues then assist in resolution. 

Do this in your spare time or if you want to use someone else's tool and you hit issues. Especially all tools created recently and that are on usegalaxy.eu
@simonbray @tsenapathi

**Comment by simonbray** [comment]
As far as I'm concerned we can close this. Unless you would like to do some reviewing of my gromacs tools @tsenapathi?
