### ISSUE TITLE
AMBER

### ISSUE THREAD

**Issue by josoga2** [galaxycomputationalchemistry/galaxy-tools-compchem#57]
I will like to request that AmberMD (http://ambermd.org/) as a package be part of the compchem galaxy tools. It provides special features for nucleic acid simulation. 

Thanks

**Comment by bgruening** [comment]
Hi @josoga2, afaik AMBER is not open source and we can not distribute it without paying a lot of money. See here http://ambermd.org/LicenseAmber18.pdf and here http://ambermd.org/GetAmber.php. And even if we pay the fee, we are not allowed to offer it easily through our server cheminformatics.usegalaxy.eu :(

Or are you asking for the amber-tools? Are those useful without Amber? I'm sorry but dealing with non-open source software is always complicated, espeically if we focus on reproducibility and accessibilty.

**Comment by josoga2** [comment]
OK. I never knew of this complication. The galaxy tools has really been a life saver, and I thought it would be great if amber was part of the tools on galaxy. 

Thanks for the prompt response. I will close the issue right away.

**Comment by bgruening** [comment]
Thanks for your feedback, we agree that it would be phenomenal to include Amber ... :(

Do you think the amber-tools, which are open source are useful for you?

**Comment by josoga2** [comment]
Yes, they are useful. Especially for RNA-Protein complex simulation.

**Comment by chrisbarnettster** [comment]
@josaga2 We’ve got some ambertools and I’ve been making some more wrappers.
What else will be helpful?

**Comment by simonbray** [comment]
Hi @josoga2, I don't have much experience with MD simulations of RNA but it should be possible to set them up using the GROMACS tools.

As for Amber, as Björn said we can only use open source tools. Amber only provides the following tools under an open-source license: http://ambermd.org/AmberTools.php. If any of these are useful for you, let us know. We already integrated some of them, e.g. Antechamber, tleap.
