### ISSUE TITLE
About GROMACS

### ISSUE THREAD

**Issue by josoga2** [galaxycomputationalchemistry/galaxy-tools-compchem#63]
Hi,
Was there a recent upgrade on the GROMACS tool available on [https://cheminformatics.usegalaxy.eu/].
The final production simulation tab seems to be a duplication of the NPT simulation. Please help !!!

**Comment by simonbray** [comment]
I recommend you use this newer tool: https://cheminformatics.usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fchemteam%2Fgmx_md%2Fgmx_md%2F2019.1

It can be used for both NVT and NPT simulations.

All the best, Simon

**Comment by bgruening** [comment]
@josoga2 please also note that you can always switch back to old versions of this tool by using the version button at the top of your tool form.

![grafik](https://user-images.githubusercontent.com/469983/75605516-d2447800-5ae3-11ea-81d1-754c1448900f.png)

**Comment by josoga2** [comment]
Hi,
great. Its fast working for me. Thanks for the help
