### ISSUE TITLE
Travis job is blocking PR merges

### ISSUE THREAD

**Issue by simonbray** [galaxycomputationalchemistry/galaxy-tools-compchem#86]
Since we replaced Travis with Github Actions PRs can't be merged, as the old Travis job is still there and gets stuck with `Expected — Waiting for status to be reported`. The result is that non-admins (e.g. @tsenapathi and I) can't merge PRs any more since the CI successfully completing is a condition for merging.

Somehow the job needs to be removed on the Travis side, maybe these links help?

- https://stackoverflow.com/questions/30874853/how-do-you-remove-a-github-repository-for-travis-ci-tests
- https://github.com/travis-ci/travis-ci/issues/987

**Comment by bgruening** [comment]
@simonbray I tried to fix it, can you please test and let me know? Thanks.

**Comment by simonbray** [comment]
I think it worked, thanks @bgruening! I can read `All checks have passed` below the PR now, which wasn't the case before.
